#ifndef INPUTMETHODMODIFIER_GLOBAL_H
#define INPUTMETHODMODIFIER_GLOBAL_H

#if defined(INPUTMETHODMODIFIER_LIBRARY)
#  define INPUTMETHODMODIFIER_EXPORT Q_DECL_EXPORT
#else
#  define INPUTMETHODMODIFIER_EXPORT Q_DECL_IMPORT
#endif

#endif // INPUTMETHODMODIFIER_GLOBAL_H
